# -*- coding: utf-8 -*-
"""SKS_DA_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yFJq-0n3R_PM0GgES0gLmr4ya5G9QU3g

# 📘 **SAIKET SYSTEMS INTERNSHIP - TASK 5✅**
---
# ✅ "PROJECT-CUSTOMER CHURN ANALYSIS AND PREDICTION"
---
**5.RETENTION STRATEGIES & LTV**
---

~BY AKASH. V

---

# 🎯 **Task Description:**
# - Propose strategies to reduce churn
# - Identify key factors influencing churn
# - Calculate customer lifetime value (LTV)
# - Find high-value customers at risk

# 1️⃣ Import Required Libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier

"""# 2️⃣ Load Cleaned Dataset"""

df = pd.read_csv("cleaned_churn_data.csv")

"""# 3️⃣ Feature Importance via Random Forest"""

X = df.drop("Churn", axis=1)
y = df["Churn"]

model = RandomForestClassifier(random_state=42)
model.fit(X, y)

importances = pd.Series(model.feature_importances_, index=X.columns)
important_features = importances.sort_values(ascending=False)[:10]

# Plot top 10 features
plt.figure(figsize=(10,6))
important_features.plot(kind='barh', color='skyblue')
plt.title("Top 10 Features Influencing Churn")
plt.xlabel("Feature Importance")
plt.gca().invert_yaxis()
plt.show()

"""# 4️⃣ Calculate LTV = Average Monthly Charges * Tenure
# (Assuming all customers are of equal profitability)
"""

df['LTV'] = df['MonthlyCharges'] * df['tenure']

"""# 5️⃣ High Value + At-Risk Customers
# High LTV customers who churned
"""

df_high_value_risk = df[(df['Churn'] == 1) & (df['LTV'] > df['LTV'].quantile(0.75))]
print("\n⚠️ High-Value Customers at Risk of Churn:")
print(df_high_value_risk[['tenure', 'MonthlyCharges', 'LTV']].head())

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_high_value_risk, x='tenure', y='MonthlyCharges', size='LTV', hue='gender_Male', alpha=0.6, sizes=(50, 500))
plt.title('Tenure vs Monthly Charges for High-Value At-Risk Customers (Size based on LTV, Color based on Gender)')
plt.xlabel('Tenure')
plt.ylabel('Monthly Charges')
plt.grid(True)
plt.show()

"""# 6️⃣ Retention Strategy Suggestions (Markdown Summary)

## 🛠️ Suggested Retention Strategies:

1. 📞 Target high-LTV customers with loyalty offers or personalized outreach.
2. 🧾 Simplify or adjust long-term contracts to match top churn contracts.
3. 💳 Offer alternative payment methods to customers with high churn history.
4. 📊 Educate and engage customers early during 0–12 month tenure period.
5. 🎯 Use top 10 churn features to proactively intervene (e.g., No tech support, monthly contract, fiber service).

# 📈 **Skills Gained:**
# - Data-driven decision-making
# - Customer analytics & segmentation
# - LTV calculation logic

### ✅ **Conclusion – Task 5: Retention Strategies & Lifetime Value (LTV)**

In this task, we identified key features influencing churn using feature importance from a Random Forest model and calculated Customer Lifetime Value (LTV) to assess the long-term worth of each customer. We also detected high-value customers at risk of churning and proposed actionable retention strategies based on these insights.

This task bridges data analysis with real-world business impact, helping organizations reduce churn and improve long-term profitability through targeted interventions.


**~AKASH. V - DATA ANALYSIS INTERN AT SAIKET SYSTEMS**
"""